ashmoret-helm:
  objects:

    - name: frontend
      type: deployment
      tag: 32031eb5ff38
      replicas: 1

      service:
        enabled: true
        port: 80
        targetPort: 80

      resources:
        requests:
          cpu: 250m
          memory: 400Mi
        limits:
          cpu: 500m
          memory: 800Mi

      configMap:
        enabled: true
        data:
          APP_ENV: production
